[[main]]
  identifier = "posts"
  name = "ğŸ“ƒ æ–‡ç« "
  url = "posts"
  weight = 1

[[main]]
  identifier = "archive"
  name = "ğŸ“¦ å½’æ¡£"
  url = "archive"
  weight = 2

[[main]]
  parent = "archive"
  name = "ğŸ›  æŠ˜è…¾"
  url = "categories/æŠ˜è…¾"

[[main]]
  parent = "archive"
  name = "â³ æ—¶å…‰"
  url = "categories/æ—¶å…‰"

[[main]]
  parent = "archive"
  name = "ğŸª çº¸å±‘"
  url = "categories/çº¸å±‘"

[[main]]
  identifier = "showcase"
  name = "ğŸ”— é“¾æ¥"
  url = "showcase"
  weight = 3

[[main]]
  identifier = "gallery"
  name = "ğŸ“· ç”»å»Š"
  url = "gallery"
  weight = 4

[[main]]
  identifier = "daily"
  name = "â˜•ï¸ æ—¥å¸¸"
  url = "daily"
  weight = 5

[[main]]
  identifier = "love"
  name = "ğŸ’• ç›¸æ‹"
  url = "love"
  weight = 6

[[main]]
  identifier = "about"
  name = "ğŸ˜† å…³äº"
  url = "about"
  weight = 7